FROM node:20-slim

ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}
EXPOSE 5173

WORKDIR /home/node/frontend
COPY --chown=node:node frontend/package.json /home/node/frontend
RUN npm install -g npm && npm install
USER node
CMD [ "npm", "run", "dev" ]
