FROM node:21-slim

ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}
EXPOSE 5173

COPY --chown=node:node . /home/node
WORKDIR /home/node/frontend
RUN npm install
RUN npm i @chakra-ui/react @chakra-ui/next-js @emotion/react @emotion/styled framer-motion react-router-dom
USER node
RUN npm install react-icons --save
CMD [ "npm", "run", "dev" ]
