FROM golang:1.21

ENV TZ=Asia/Tokyo
EXPOSE 3000
ENV ROOT=/home/go/backend
WORKDIR ${ROOT}
ENV GOPATH=/go

RUN apt-get update && apt-get install -y git

COPY --chown=root:root backend/go.mod . 
COPY --chown=root:root backend/go.sum .
RUN go mod download

#COPY --chown=root:root backend .
#RUN go build -o main .

#CMD ["./main"]
